### ISSUE TITLE
Fix code scanning alert - Server-side request forgery

### ISSUE THREAD

**Issue by khellang** [novorender/novoweb#209]
Tracking issue for:
- [ ] https://github.com/novorender/novoweb/security/code-scanning/2

@nd-novorender Is this really a user-provided value, or a false positive?

**Comment by nd-novorender** [comment]
@khellang that's an endpoint, so user can pass any URL, but it's appended base URL `https://nyeveier.pims365.no`, so it's essentially just a proxy. Not sure if it's an issue
